export const products = [
    {
      id: 1,
      name: "نایک",
      description: [
        { support: "گارانتی مادام العمر" },
        { support: "ارسال رایگان" },
        { support: "اورجینال" },
      ],
      price: 120,
      offPrice: 120,
      discount: 0,
      image: "https://s6.uupload.ir/files/luis-felipe-lins-j2-waqdckus-unsplash_ku8a.jpg",
    },
    {
      id: 2,
      name: "ادیداس",
      description: [{ support: "گارانتی مادام العمر" }, { support: "اورجینال" }],
      price: 110,
      offPrice: 100,
      discount: 8,
      image: "https://s6.uupload.ir/files/luis-felipe-lins-j2-waqdckus-unsplash_ku8a.jpg",
    },
    {
      id: 3,
      name: "ونس",
      description: [
        { support: "گارانتی مادام العمر" },
        { support: "اورجینال" },
        { support: "ارسال رایگان" },
      ],
      price: 99,
      offPrice: 89,
      discount: 10,
      image: "https://s6.uupload.ir/files/luis-felipe-lins-j2-waqdckus-unsplash_ku8a.jpg",
    },
    {
      id: 4,
      name: "نایک",
      description: [
        { support: "گارانتی مادام العمر" },
        { support: "اورجینال" },
        { support: "ارسال رایگان" },
      ],
      price: 260,
      offPrice: 220,
      discount: 15,
      image: "https://s6.uupload.ir/files/luis-felipe-lins-j2-waqdckus-unsplash_ku8a.jpg",
    },
    {
      id: 5,
      name: "ال استار",
      description: [
        { support: "گارانتی مادام العمر" },
        { support: "اورجینال" },
        { support: "ارسال رایگان" },
      ],
      price: 150,
      offPrice: 150,
      discount: 0,
      image: "https://s6.uupload.ir/files/luis-felipe-lins-j2-waqdckus-unsplash_ku8a.jpg",
    },
    {
      id: 6,
      name: "پوما",
      description: [
        { support: "گارانتی مادام العمر" },
        { support: "اورجینال" },
        { support: "ارسال رایگان" },
      ],
      price: 220,
      offPrice: 200,
      discount: 13,
      image: "https://s6.uupload.ir/files/luis-felipe-lins-j2-waqdckus-unsplash_ku8a.jpg",
    },
  ];
  